In [1]:
# Reload all modules at every code execution
%load_ext autoreload
%autoreload 2

In [14]:
import pandas as pd
from pfas_trace.config import DATASET_FILE
from pfas_trace.transform import load_and_transform

from pfas_trace.config import setup_logging

setup_logging()

In [3]:
df = pd.read_parquet(DATASET_FILE).query('country=="France"')

In [15]:
df_features = load_and_transform(df)
df_features.head()

2026-10-09 23:52:07,752 :: pfas_trace.transform :: INFO :: unoptimized dataframe size: 499.00 MB
2026-10-09 23:52:08,571 :: pfas_trace.transform :: INFO :: optimized dataframe size: 270.00 MB (-45.89%)

,date,lat,lon,name,city,pfas_sum,producer_distance_min,producer_count_0_5km,producer_count_5_25km,producer_count_25_50km,...,treatment_and_disposal_of_hazardous_waste_count_5_25km,treatment_and_disposal_of_hazardous_waste_count_25_50km,treatment_and_disposal_of_non_hazardous_waste_distance_min,treatment_and_disposal_of_non_hazardous_waste_count_0_5km,treatment_and_disposal_of_non_hazardous_waste_count_5_25km,treatment_and_disposal_of_non_hazardous_waste_count_25_50km,waste_management_site_distance_min,waste_management_site_count_0_5km,waste_management_site_count_5_25km,waste_management_site_count_25_50km
0,2011-04-27,50.885284,1.662663,BSS000AENC,Wissant,0.0,187.225952,0.0,0.0,0.0,...,0.0,4.0,47.694805,0.0,0.0,2.0,14.34426,0.0,4.0,4.0
1,2013-06-07,50.885284,1.662663,BSS000AENC,Wissant,0.0,187.225952,0.0,0.0,0.0,...,0.0,4.0,47.694805,0.0,0.0,2.0,14.34426,0.0,4.0,4.0
2,2015-01-23,50.885284,1.662663,BSS000AENC,Wissant,0.0,187.225952,0.0,0.0,0.0,...,0.0,4.0,47.694805,0.0,0.0,2.0,14.34426,0.0,4.0,4.0
3,2017-09-12,50.885284,1.662663,BSS000AENC,Wissant,0.0,187.225952,0.0,0.0,0.0,...,0.0,4.0,47.694805,0.0,0.0,2.0,14.34426,0.0,4.0,4.0
4,2021-02-23,50.885284,1.662663,BSS000AENC,Wissant,0.0,187.225952,0.0,0.0,0.0,...,0.0,4.0,47.694805,0.0,0.0,2.0,14.34426,0.0,4.0,4.0

In [18]:
df_features.query('pfas_sum > 0')

,date,lat,lon,name,city,pfas_sum,producer_distance_min,producer_count_0_5km,producer_count_5_25km,producer_count_25_50km,...,treatment_and_disposal_of_hazardous_waste_count_5_25km,treatment_and_disposal_of_hazardous_waste_count_25_50km,treatment_and_disposal_of_non_hazardous_waste_distance_min,treatment_and_disposal_of_non_hazardous_waste_count_0_5km,treatment_and_disposal_of_non_hazardous_waste_count_5_25km,treatment_and_disposal_of_non_hazardous_waste_count_25_50km,waste_management_site_distance_min,waste_management_site_count_0_5km,waste_management_site_count_5_25km,waste_management_site_count_25_50km
31,2019-01-16,50.946739,1.756680,BSS000AEYW,Sangatte,1.0,191.718246,0.0,0.0,0.0,...,0.0,4.0,39.740410,0.0,0.0,2.0,6.612189,0.0,2.0,7.0
155,2021-11-29,50.832870,1.713737,BSS000AFNH,Leulinghen-Bernes,0.6,180.552063,0.0,0.0,0.0,...,0.0,4.0,44.801426,0.0,0.0,2.0,15.037172,0.0,4.0,5.0
164,2024-08-27,50.832870,1.713737,BSS000AFNH,Leulinghen-Bernes,2.0,180.552063,0.0,0.0,0.0,...,0.0,4.0,44.801426,0.0,0.0,2.0,15.037172,0.0,4.0,5.0
167,2011-05-25,50.769669,1.609978,BSS000AFNL,Wimereux,2.0,176.460495,0.0,0.0,0.0,...,0.0,3.0,50.837372,0.0,0.0,0.0,6.497359,0.0,2.0,6.0
206,2020-07-01,50.769669,1.609978,BSS000AFNL,Wimereux,8.0,176.460495,0.0,0.0,0.0,...,0.0,3.0,50.837372,0.0,0.0,0.0,6.497359,0.0,2.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
732686,2024-03-15,45.625134,4.666310,1-ZS1-AD-170324,Mornant,3460.0,15.444668,0.0,2.0,0.0,...,1.0,4.0,15.163979,0.0,3.0,4.0,9.106387,0.0,6.0,16.0
732687,2024-03-15,45.555317,4.803987,2-ZS1-NB-180324,Loire-sur-Rhône,6500.0,17.064194,0.0,2.0,0.0,...,2.0,2.0,15.340144,0.0,3.0,4.0,1.981921,1.0,6.0,15.0
732688,2024-03-15,45.717377,5.023562,1-ZE-GL-230324,Genas,8660.0,15.390146,0.0,2.0,0.0,...,3.0,3.0,14.114435,0.0,4.0,3.0,8.491023,0.0,11.0,8.0
732689,2024-03-15,45.796604,5.070755,2-ZE-FPL-130324,Jons,630.0,21.382191,0.0,2.0,0.0,...,2.0,2.0,12.329144,0.0,4.0,3.0,2.643232,1.0,8.0,10.0
732690,2024-03-15,45.775429,4.730953,1-ZN-TG-170324,Tassin-la-Demi-Lune,1930.0,10.190081,0.0,2.0,0.0,...,1.0,5.0,10.020327,0.0,6.0,0.0,11.321350,0.0,10.0,11.0